# Generated by Django 4.0.2 on 2022-02-06 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('friendlyName', models.CharField(max_length=64, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='smarthome_images')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Type of Rooms',
            },
        ),
        migrations.CreateModel(
            name='SensorsDataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('friendlyName', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Type of Data from Sensors',
            },
        ),
        migrations.CreateModel(
            name='SettingsAgentsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=50, unique=True)),
                ('sshUser', models.CharField(max_length=20)),
                ('sshPrivateKey', models.TextField(blank=True, max_length=4120)),
            ],
        ),
        migrations.CreateModel(
            name='SettingsSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('output_number', models.IntegerField(unique=True)),
                ('url_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SettingsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('settingsValueString', models.CharField(blank=True, max_length=128)),
                ('settingsValueBoolean', models.BooleanField(blank=True)),
                ('settingsSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarthome.settingssections')),
                ('settingsType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarthome.settingstype')),
            ],
        ),
        migrations.CreateModel(
            name='SensorsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='smarthome_images')),
                ('short_description', models.CharField(blank=True, max_length=64)),
                ('unit', models.CharField(blank=True, max_length=8)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smarthome.sensorsdatatype')),
            ],
            options={
                'verbose_name_plural': 'Type of Sensors',
            },
        ),
        migrations.CreateModel(
            name='SensorsLocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(max_length=64)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarthome.rooms')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarthome.sensorstype')),
            ],
            options={
                'verbose_name_plural': 'Sensors Locate',
            },
        ),
        migrations.CreateModel(
            name='SensorsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sensorName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarthome.sensorslocate')),
            ],
            options={
                'verbose_name_plural': 'Sensors Data',
            },
        ),
        migrations.AddField(
            model_name='rooms',
            name='roomType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smarthome.roomtype'),
        ),
    ]
