---
all:
  hosts:
    HomeAssistantServer:
      ansible_host: 172.20.1.15
    HomeAssistantClient:
      ansible_host: 172.20.1.16

  children:
    server:
      hosts:
        HomeAssistantServer:
    client:
      hosts:
        HomeAssistantClient:
          

...